---

- hosts: proxmox
vars_prompt:

    - name: String
      prompt: What is your username?
      private: false
  tasks:
  - name: Creating an empty file
    file:
      path: "/root/test123 {{ String }}"
      state: touch
